<div class="alert alert-block alert-info" style="margin-top: 20px">
    <h1 align=center>Data 1202: Data Analytics Tools</h1>
    <h1 align=center>Assignment-4</h1>
</div>

In [1]:
#Import Python Libraries
import pandas as pd
from sqlalchemy import create_engine
import pymysql

In [2]:
#Reading csv file 
df = pd.read_csv("youtube_dataset.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 582: invalid start byte

In [3]:
#Reading csv file 
df = pd.read_csv("youtube_dataset.csv", encoding='latin-1')

In [4]:
#Understanding the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3944 entries, 0 to 3943
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   web-scraper-order      3944 non-null   object
 1   web-scraper-start-url  3944 non-null   object
 2   userID                 3944 non-null   object
 3   userID-href            3944 non-null   object
 4   name                   3944 non-null   object
 5   uploads                3944 non-null   int64
 6   subscribers            3944 non-null   int64
 7   videoviews             3944 non-null   int64
 8   country                3650 non-null   object
 9   channeltype            3681 non-null   object
 10  usercreated            3944 non-null   object
 11  grade                  3944 non-null   object
 12  YouTube_Link           59 non-null     object
 13  YouTube_Link-href      3885 non-null   object
 14  TwitterHandle          52 non-null     object
 15  TwitterHandle-href     3334 non-null   object
 16  InstagramHandle        42 non-null     object
 17  InstagramHandle-href   3885 non-null   object
 18  MonthlyEarnings        3944 non-null   object
 19  YearlyEarnings         3944 non-null   object
dtypes: int64(3), object(17)
memory usage: 616.4+ KB

In [5]:
#understanding the shape of the dataframe 
total_rows, total_columns = df.shape
print(f'Total Rows: {total_rows}, Total Columns: {total_columns}')

Total Rows: 3944, Total Columns: 20

In [6]:
#looking at the top five data 
df.head()

,web-scraper-order,web-scraper-start-url,userID,userID-href,name,uploads,subscribers,videoviews,country,channeltype,usercreated,grade,YouTube_Link,YouTube_Link-href,TwitterHandle,TwitterHandle-href,InstagramHandle,InstagramHandle-href,MonthlyEarnings,YearlyEarnings
0,1553043067-5148,https://socialblade.com/youtube/top/5000/mosts...,PewDiePie,https://socialblade.com/youtube/c/pewdiepie,PewDiePie,3779,90210848,20772365682,US,Entertainment,"Apr 29th, 2010",A,NaN,https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...,NaN,https://twitter.com/pewdiepie,NaN,https://instagram.com/pewdiepie,66.9K - 1.1M,802.3K - 12.8M
1,1553043063-5147,https://socialblade.com/youtube/top/5000/mosts...,T-Series,https://socialblade.com/youtube/c/tseriesmusic,T-Series,13218,90194329,65092058996,IN,Music,"Mar 13th, 2006",A++,NaN,https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...,NaN,https://instagram.com/tseries.official,NaN,https://plus.google.com/115156822320080163368,635.6K - 10.2M,7.6M - 122M
2,1553043059-5146,https://socialblade.com/youtube/top/5000/mosts...,Gaming,https://socialblade.com/youtube/channel/UCOpNc...,Gaming,0,81888222,0,NaN,Games,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,NaN,NaN,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,0 - 0,0 - 0
3,1553043055-5145,https://socialblade.com/youtube/top/5000/mosts...,YouTube Movies,https://socialblade.com/youtube/channel/UClgRk...,YouTube Movies,0,77413743,0,NaN,Film,"Jun 10th, 2015",D-,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,NaN,NaN,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,0 - 0,0 - 0
4,1553043051-5144,https://socialblade.com/youtube/top/5000/mosts...,Sports,https://socialblade.com/youtube/channel/UCEgdi...,Sports,0,75622870,0,NaN,Sports,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,NaN,NaN,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,0 - 0,0 - 0

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <h3 align=center>Create a function to calculate the distribution of channeltype from the top 1000 records.</h3>
    
</div>

In [7]:
#creating function name channeltype  
def channeltype(data):
    #getting first 1000 records uisng iloc
    top_1000 = data.iloc[0:1000]
    # Getting  the distribution of 'channeltype' values
    distribution = top_1000['channeltype'].value_counts( )
    # Getting the percentage of each 'channeltype' in the top 1000 records
    percentage= distribution / len(top_1000) * 100
    # Create a DataFrame with 'channeltype', 'Count', and 'Percentage' columns
    result_table = pd.DataFrame({
        'channeltype': distribution.index,
        'Count': distribution.values,
        'Percentage': percentage.values
    })

    # Return the DataFrame
    return result_table

In [8]:
#Calling the 'channeltype' function with the DataFrame 'df'
dis = channeltype(df)

In [9]:
#viewing the  distribution of 'channeltype' values in the top 1000 rows of the DataFrame
dis

      channeltype  Count  Percentage
0   Entertainment    284        28.4
1           Music    240        24.0
2           Games    115        11.5
3          Comedy     76         7.6
4          People     72         7.2
5           Howto     49         4.9
6            Film     36         3.6
7       Education     30         3.0
8            Tech     19         1.9
9          Sports     17         1.7
10           News     17         1.7
11          Autos      3         0.3
12        Animals      2         0.2
13      Nonprofit      1         0.1
14         Travel      1         0.1

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <h3 align=center>Load only the top 1000 records of the original 4000 into a separate CSV file, and to a database table.</h3>
    
</div>

In [10]:
#getting the top 1000 records 
top_1000 = df.iloc[0:1000]

In [11]:
#Save to CSV named top_1000_channels
top_1000.to_csv("top_1000_channels.csv", index=False)

In [12]:
# Get the shape of the result
result_shape = top_1000.shape
print(f'Shape of the result: {result_shape}')

Shape of the result: (1000, 20)

In [13]:
#Create the engine with the MySQL dialect and the appropriate connection details
engine = create_engine('mysql+pymysql://group10:assig****@localhost/assign****')

# Assuming 'your_dataframe' is the DataFrame you want to save
top_1000.to_sql('top_1000_youtube_channels', con=engine, if_exists='replace', index=False)

1000